In [1]:
import re 
import os
import matplotlib.pyplot as plt
import numpy as np 
import tensorflow as tf


print(tf.__version__)




file_dir = 'D:\\DataSet\\project_material\\result\\'

2.3.0


In [2]:
f = open('atom.txt','r',encoding='UTF-8')
atom_matter = {}
for line in f.readlines():
    if(len(line)>0):
#     print(line.split()[0])
        number = re.findall(r'\d+\.?\d+?',line.split()[1])
        atom_syb = line.split()[0]
        atom_matter[atom_syb] = float(number[0])

    
#建立原子质量表，用于取代原子符号


pass


In [3]:
print(atom_matter)
print(type(atom_matter['He']))

{'H': 1.0, 'He': 4.0, 'Li': 6.9, 'Be': 9.0, 'B': 10.8, 'C': 12.0, 'N': 14.0, 'O': 15.9, 'F': 18.9, 'Ne': 20.1, 'Na': 22.9, 'Mg': 24.3, 'Al': 26.9, 'Si': 28.0, 'P': 30.9, 'S': 32.0, 'Cl': 35.4, 'Ar': 39.9, 'K': 39.0, 'Ca': 40.0, 'Sc': 44.9, 'Ti': 47.8, 'V': 50.9, 'Cr': 51.9, 'Mn': 54.9, 'Fe': 55.8, 'Co': 58.9, 'Ni': 58.6, 'Cu': 63.5, 'Zn': 65.3, 'Ga': 69.7, 'Ge': 72.6, 'As': 74.9, 'Se': 78.9, 'Br': 79.9, 'Kr': 83.7, 'Rb': 85.4, 'Sr': 87.6, 'Y': 88.9, 'Zr': 91.2, 'Nb': 92.9, 'Mo': 95.9, 'Tc': 98.9, 'Ru': 101.0, 'Rh': 102.9, 'Pd': 106.4, 'Ag': 107.8, 'Cd': 112.4, 'In': 114.8, 'Sn': 118.7, 'Sb': 121.7, 'Te': 127.6, 'I': 126.9, 'Xe': 131.2, 'Cs': 132.9, 'Ba': 137.3, 'La': 138.9, 'Ce': 140.1, 'Pr': 140.9, 'Nd': 144.2, 'Pm': 144.9, 'Sm': 150.3, 'Eu': 151.9, 'Gd': 157.2, 'Tb': 158.9, 'Dy': 162.5, 'Ho': 164.9, 'Er': 167.2, 'Tm': 168.9, 'Yb': 173.0, 'Lu': 174.9, 'Hf': 178.4, 'Ta': 180.9, 'W': 183.8, 'Re': 186.2, 'Os': 190.2, 'Ir': 192.2, 'Pt': 195.0, 'Au': 196.9, 'Hg': 200.5, 'Tl': 204.3, 'Pb': 

In [4]:
# set_center_gravity(coor_mat[10])
# print(coor_mat[10])

In [5]:
def set_center_gravity(array):
    array = array.reshape(int(len(array)/4),4)
    for i in range(1,4):
        mean_center = np.mean(array[:,i])

        array[:,i] = array[:,i] - [mean_center] * len(array[:,i])
    arr = array.reshape(-1,)

    return arr

import scipy.linalg as linalg
import matplotlib as mpl 
from mpl_toolkits.mplot3d import Axes3D 
import matplotlib.pyplot as plt 
#旋转矩阵 欧拉角
def rotate_mat(axis, radian):
    rot_matrix = linalg.expm(np.cross(np.eye(3), axis / linalg.norm(axis) * radian))
    return rot_matrix

energy_mat = []
coor_mat =[]
for file_name in os.listdir(file_dir):
#     print(file_name)
    f = open(file_dir + file_name)
    coor_sequence =[]
    for line in f.readlines():
        line = line.strip()
        if line in atom_matter:
            line = atom_matter[line]
        coor_sequence.append(float(line))
        energy = line
    energy_mat.append(np.array(float(energy)))
    
    coor_sequence.pop(len(coor_sequence)-1)
    coor_sequence = set_center_gravity(np.array(coor_sequence))

    coor_sequence =list(coor_sequence) + [0] *(1000-len(coor_sequence))
    coor_mat.append(np.array(coor_sequence))
    

energy_mat = energy_mat[0:5200]
coor_mat = coor_mat[0:5200]


# reshape
coor_mat_reshape = []
for item in coor_mat:
#     print(len(item))
    item = item.reshape(250,4)
    coor_mat_reshape.append(np.array(item))

# print(len(coor_mat_reshape[0]))
# print(type(coor_mat_reshape[0]))
# coor_mat_reshape_array = np.array(coor_mat_reshape)
print(coor_mat_reshape[10])


# reshape
coor_mat_reshape = []
for item in coor_mat:
#     print(len(item))
    item = item.reshape(250,4)
    coor_mat_reshape.append(np.array(item))

# print(len(coor_mat_reshape[0]))
# print(type(coor_mat_reshape[0]))
# coor_mat_reshape_array = np.array(coor_mat_reshape)
print(coor_mat_reshape[10])

pure_coor_mat = [np.array(item)[:,1:4] for item in coor_mat_reshape]
pure_atom_matter = [np.array(item)[:,0:1] for item in coor_mat_reshape] * 12
print(pure_coor_mat[0])
print(pure_atom_matter[0])


coor_mat_rotate = []
energy_mat_rotate = energy_mat * 12
for rot_index in range(0,12):
    
    rot_mat = rotate_mat([0,0,1], rot_index * 3.1415/(12*180))
#     print(rot_mat)
    for i in range(len(coor_mat)):
        single = []
        for item in pure_coor_mat[i]:
            
            x1 = np.dot(rot_mat, item)
            single.append(x1)
        coor_mat_rotate.append(single)
        
        
print(len(coor_mat_rotate))      
print(len(energy_mat_rotate))
# print(len(coor_mat))
print(len(coor_mat_rotate[0]))      
print(len(pure_atom_matter[0]))


coor_mat_after_rotate = []
for i in range(len(pure_atom_matter)):
    temp = np.hstack((pure_atom_matter[i],coor_mat_rotate[i]))
    coor_mat_after_rotate.append(temp)

    
    
print(len(coor_mat_after_rotate))
print(len(energy_mat_rotate))
print(coor_mat_after_rotate[0])
#time to train!!!



[[ 1.20000000e+01 -6.78494831e+00  2.85676190e+00 -2.83961518e+00]
 [ 1.20000000e+01 -5.23718629e+00  8.90469052e-01 -1.68942075e+00]
 [ 1.40000000e+01 -2.91426669e+00  1.89479608e+00 -1.04793194e+00]
 [ 1.20000000e+01 -2.98534229e+00  4.46809542e+00 -1.48292028e+00]
 [ 1.20000000e+01 -5.36577087e+00  5.11148586e+00 -2.70947259e+00]
 [ 1.40000000e+01 -1.27815333e+00  6.15631328e+00 -8.04820120e-01]
 [ 1.20000000e+01  9.44359993e-01  5.51052657e+00  1.30714760e-01]
 [ 1.40000000e+01  1.93595938e+00  3.10747292e+00  2.54038668e-01]
 [ 1.20000000e+01  4.40597209e+00  3.27830243e+00  1.05591112e+00]
 [ 1.20000000e+01  4.99862592e+00  5.90562635e+00  1.63353248e+00]
 [ 1.20000000e+01  2.81075340e+00  7.31647820e+00  1.04877265e+00]
 [ 1.40000000e+01  6.06842543e+00  1.41886439e+00  1.15872395e+00]
 [ 1.40000000e+01  3.02442429e+00 -1.93477493e+00  5.39321364e-01]
 [ 1.20000000e+01  3.18489205e+00 -4.54051685e+00  5.61575599e-01]
 [ 1.20000000e+01  5.83697098e+00 -5.28249577e+00  5.33886358e

62400
62400
250
250
62400
62400
[[ 1.20000000e+01  8.42323361e+00 -1.31228433e+00  2.25560936e+00]
 [ 1.20000000e+01  9.61959536e+00 -3.75107216e+00  2.41936761e+00]
 [ 1.20000000e+01  8.13005727e+00 -5.91316650e+00  1.84931699e+00]
 [ 1.20000000e+01  5.61027318e+00 -5.63179760e+00  1.19387446e+00]
 [ 1.20000000e+01  4.37996978e+00 -3.23036341e+00  1.04712538e+00]
 [ 1.20000000e+01  5.92160047e+00 -1.08136436e+00  1.59067505e+00]
 [ 1.59000000e+01  4.31727298e+00 -7.82971938e+00  6.54708712e-01]
 [ 1.20000000e+01  1.78660396e+00 -7.74744577e+00  3.49275529e-02]
 [ 1.20000000e+01  4.74975197e-01 -5.39153088e+00 -1.04991343e-01]
 [ 1.20000000e+01  1.80000733e+00 -3.09876827e+00  3.29307581e-01]
 [ 1.20000000e+01  6.40822141e-01 -1.00561599e+01 -4.35235018e-01]
 [ 1.20000000e+01 -1.96614083e+00 -1.01565494e+01 -1.07753273e+00]
 [ 1.20000000e+01 -3.33662753e+00 -7.80673903e+00 -1.16813158e+00]
 [ 1.20000000e+01 -2.15131707e+00 -5.53930720e+00 -7.10212771e-01]
 [ 1.20000000e+01  9.82523673e

In [6]:

# print(len(coor_mat[0]))
X = np.asarray(coor_mat_after_rotate)
Y = np.asarray(energy_mat_rotate)
# print(len(X[5]))
np.save('energy_rotate.npy',energy_mat_rotate)
np.save('coordinate_rotate.npy',coor_mat_after_rotate)


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.05)
print(len(X))
print(len(y_test))

62400
3120


In [8]:
print(len(x_train))
print(len(x_test))
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU') 
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
            logical_gpus = tf.config.experimental.list_logical_devices('GPU')
            print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

59280
3120
1 Physical GPUs, 1 Logical GPUs


In [28]:
import tensorflow as tf
import numpy as np
from numba import cuda
# cuda.select_device(0)

model = tf.keras.models.Sequential([
#    tf.keras.layers.Embedding(1000,8,input_length = 1000,mask_zero = True),
#     tf.keras.layers.Flatten(),
#     tf.keras.layers.Masking(mask_value = 0),
#     tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation='relu'),
    tf.keras.layers.Dense(1000, activation='relu'),
    tf.keras.layers.Dense(1000, activation='relu'),
    tf.keras.layers.Dense(50, activation='relu'),
      
  tf.keras.layers.Dense(1, activation='linear')
])

# model = tf.keras.Sequential() #layers [1,50,50,50,50,1]
# model.add(tf.keras.layers.Masking(mask_value=0))

# model.add(tf.keras.layers.LSTM(input_shape=(250,4),units=50,return_sequences=True,activation='relu'))


# model.add(tf.keras.layers.LSTM(input_shape=(None,1),units=50,return_sequences=True,activation='relu'))

# model.add(tf.keras.layers.LSTM(input_shape=(None,1),units=50,return_sequences=True,activation='relu'))

# model.add(tf.keras.layers.LSTM(50,return_sequences=False,activation='relu'))

# model.add(tf.keras.layers.Dense(units=1,activation='relu'))

# model.add(Activation("sigmoid"))


In [29]:
print(len(coor_mat_after_rotate))

62400


In [30]:
# import tensorflow as tf
# from  keras.optimizers import SGD
# learning_rate=0.1
# decay_rate=learning_rate/epochs
# momentum=0.8
# sgd=SGD(lr=learning_rate, momentum=momentum, nesterov=False)
    

In [31]:
model.compile(optimizer='rmsprop',
              loss='MSE'
              )


In [ ]:
checkpoint_path = "training_1/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 period=10,
                                                 verbose=1)


# earlystop_callback = EarlyStopping(
#   monitor='val_accuracy', min_delta=0.0001,
#   patience=1)


    
with tf.device('gpu:1'):
    model.fit(x_train, y_train,
          epochs=200,
          validation_data=(x_test,y_test),
          callbacks=[cp_callback],
        )


Epoch 1/200
1853/1853 [==============================] - 79s 43ms/step - loss: 18942630.0000 - val_loss: 21779028.0000
Epoch 2/200
1853/1853 [==============================] - 77s 42ms/step - loss: 18341566.0000 - val_loss: 21975130.0000
Epoch 3/200
1853/1853 [==============================] - 78s 42ms/step - loss: 18166254.0000 - val_loss: 21274064.0000
Epoch 4/200
1853/1853 [==============================] - 77s 41ms/step - loss: 18040616.0000 - val_loss: 21938744.0000
Epoch 5/200
1853/1853 [==============================] - 77s 42ms/step - loss: 17980090.0000 - val_loss: 21662570.0000
Epoch 6/200
1853/1853 [==============================] - 78s 42ms/step - loss: 17884574.0000 - val_loss: 21103690.0000
Epoch 7/200
1853/1853 [==============================] - 77s 42ms/step - loss: 17805160.0000 - val_loss: 21148498.0000
Epoch 8/200
1853/1853 [==============================] - 77s 42ms/step - loss: 17739174.0000 - val_loss: 21011282.0000
Epoch 9/200
1298/1853 [====================>....

In [ ]:
# latest = tf.train.latest_checkpoint(checkpoint_dir)
# print(latest)
model.evaluate(x_test,y_test,verbose=2)
# new_model = tf.keras.models.load_model('model//ann_2.h5')
# new_model.evaluate(x_test,y_test,verbose=2)
model.summary()


In [ ]:

np.set_printoptions(threshold=np.inf)
# # model = new_model
# result = new_model.predict(x_test)
result = CNN.predict(x_test)
loss_mat = [(result[i]-y_test[i])**2 for i in range(0,len(x_test))]
# KL_mat =[(result[i]-y_test) for i in range(0,len(x_test))]
# print(np.sort(loss_mat,axis = 0))
score = np.mean(np.sort(loss_mat,axis=0)[0:int(0.9 * len(loss_mat))])
# print('the biggest loss is ',big)
# print("the local of it ", local)
print(score)
plt.plot(np.sort(loss_mat,axis=0))
#now we are using a new method to do the thing:
print(len(loss_mat))

In [ ]:
# from keras.utils import plot_model
# import pydot

In [ ]:
# plot_model(model,to_file = 'model.png')

In [ ]:
hist = history.history
# print(type(history))
# print(history.history)
fig, ax = plt.subplots(1,2,figsize=(8,3))
ax[0].plot(hist['loss'], c='r', ls='--', label='train loss')
ax[0].plot(hist['val_loss'], c='orange', label='val loss')
ax[1].plot(loss_mat,c= 'green',label='preformance loss on test data')


for axis in ax:
    axis.set_xlabel('epoch')
    axis.legend();

In [ ]:
plt.plot(y_test,color = 'green')

plt.plot(new_model.predict(x_test),color ='red')
model.save('model//ann_trial_1.h5')
# model.save("D:\project_material\model")
# model.fit(train_images, 
#           train_labels,  
#           epochs=10,
#           validation_data=(test_images,test_labels),
#           callbacks=[cp_callback])  # 通过回调训练

In [89]:
# model.evaluate(X_test[0:20],Y_test[0:20],verbose = 2)
# from keras.utils import plot_model
# plot_model(model, to_file='model.png')

ModuleNotFoundError: No module named 'keras'

In [19]:
from numba import cuda
cuda.close()